#logging:
#  level:
#    ROOT: DEBUG
#  port: ${random.int[11001,12000]}

eureka:
  client:
     #下面两项没有代码提示
     serviceUrl:
      #服务治理地址
      defaultZone: http://localhost:8013/eureka/
#  instance:
#    instanceId: ${spring.application.name):${random.int}

management:
  endpoints:
    web:
      #      由于 Spring Boot 2.0 的 Actuator 只暴露了 /health、/info 两个端口（为了安全考虑）, 所以需要配置暴露的接口
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
