spring:
  datasource:
    d1:
      platform: mysql
      jdbc-url: jdbc:mysql://localhost:13306/test1?serverTimezone=GMT&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
    d2:
      platform: mysql
      #      HikariDataSource
      jdbc-url: jdbc:mysql://localhost:13306/test2?serverTimezone=GMT&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        jdbc:
          batch_size: 500
          batch_versioned_data: false
        order_inserts: true
        order_updates: true
